from math import ceil, floor
from statistics import NormalDist
import math
from collections import deque

import importlib
import json
from typing import Any, Dict, List, Optional

try:
    datamodel_module = importlib.import_module("prosperity3bt.datamodel")
except ModuleNotFoundError:
    datamodel_module = importlib.import_module("datamodel")

Listing = datamodel_module.Listing
Observation = datamodel_module.Observation
Order = datamodel_module.Order
OrderDepth = datamodel_module.OrderDepth
ProsperityEncoder = datamodel_module.ProsperityEncoder
Trade = datamodel_module.Trade
TradingState = datamodel_module.TradingState

# # values generated by MC simulations on the optimal_strat_ou_options notebook, based on the observed behavior of VEV_4000 in past sessions.
# OPTIONS = {
#     'VEV_4000': {"strike": 4000, "omega_adj": 0.7020, "avr_hold_time_up": 0.0780, "avr_hold_time_down": 0.2224},
#     'VEV_4500': {"strike": 4500, "omega_adj": 0.7012, "avr_hold_time_up": 0.0960, "avr_hold_time_down": 0.2848},
#     'VEV_5000': {"strike": 5000, "omega_adj": 0.5327, "avr_hold_time_up": 0.3614, "avr_hold_time_down": 0.2638},
#     'VEV_5100': {"strike": 5100, "omega_adj": 0.5429, "avr_hold_time_up": 0.0098, "avr_hold_time_down": 0.0611},
#     'VEV_5200': {"strike": 5200, "omega_adj": 0.5406, "avr_hold_time_up": 0.0890, "avr_hold_time_down": 0.0370},
#     'VEV_5300': {"strike": 5300, "omega_adj": 0.4306, "avr_hold_time_up": 0.0024, "avr_hold_time_down": 0.0062},
#     'VEV_5400': {"strike": 5400, "omega_adj": 0.1936, "avr_hold_time_up": 0.0320, "avr_hold_time_down": 0.2030},
#     'VEV_5500': {"strike": 5500, "omega_adj": 0.3388, "avr_hold_time_up": 0.1910, "avr_hold_time_down": 0.3868},
#     'VEV_6000': {"strike": 6000, "omega_adj": 1.0, "avr_hold_time_up": 0.0, "avr_hold_time_down": 0.0},
#     'VEV_6500': {"strike": 6500, "omega_adj": 1.0, "avr_hold_time_up": 0.0, "avr_hold_time_down": 0.0},
# }

# Underlying optimized with score 129.5203, mean PnL 148.68, std PnL 76.64, omega_adj 0.5077
# UNDERLYING: PnL = 148.7 +- 76.6, Sharpe = 129.52, omega_adj = 0.5077
# VEV_5100: PnL = 142.7 +- 73.7, Sharpe = 124.31, avr_hold_time_up = 0.0485 days, avr_hold_time_down = 0.0011 days, omega_adj = 0.4748
# VEV_5000: PnL = 139.9 +- 73.1, Sharpe = 121.66, avr_hold_time_up = 0.2350 days, avr_hold_time_down = 0.2432 days, omega_adj = 0.5410
# VEV_5200: PnL = 112.1 +- 57.3, Sharpe = 97.78, avr_hold_time_up = 0.0075 days, avr_hold_time_down = 0.0784 days, omega_adj = 0.4678
# VEV_4500: PnL = 90.8 +- 55.5, Sharpe = 76.88, avr_hold_time_up = 0.3491 days, avr_hold_time_down = 0.3654 days, omega_adj = 0.6245
# VEV_4000: PnL = 73.0 +- 48.8, Sharpe = 60.77, avr_hold_time_up = 0.2089 days, avr_hold_time_down = 0.2879 days, omega_adj = 0.6375
# VEV_5300: PnL = 56.1 +- 28.3, Sharpe = 48.97, avr_hold_time_up = 0.0306 days, avr_hold_time_down = 0.0319 days, omega_adj = 0.3740
# VEV_5400: PnL = 21.5 +- 10.3, Sharpe = 18.91, avr_hold_time_up = 0.0124 days, avr_hold_time_down = 0.1502 days, omega_adj = 0.1545
# VEV_5500: PnL = 1.9 +- 2.0, Sharpe = 1.38, avr_hold_time_up = 0.3990 days, avr_hold_time_down = 0.3931 days, omega_adj = 0.1899
OPTIONS = {
    'VEV_4000': {"strike": 4000, "omega_adj": 0.6375, "avr_hold_time_up": 0.2089, "avr_hold_time_down": 0.2879},
    'VEV_4500': {"strike": 4500, "omega_adj": 0.6245, "avr_hold_time_up": 0.3491, "avr_hold_time_down": 0.3654},
    'VEV_5000': {"strike": 5000, "omega_adj": 0.5410, "avr_hold_time_up": 0.2350, "avr_hold_time_down": 0.2432},
    'VEV_5100': {"strike": 5100, "omega_adj": 0.4748, "avr_hold_time_up": 0.0485, "avr_hold_time_down": 0.0011},
    'VEV_5200': {"strike": 5200, "omega_adj": 0.4678, "avr_hold_time_up": 0.0075, "avr_hold_time_down": 0.0784},
    'VEV_5300': {"strike": 5300, "omega_adj": 0.3740, "avr_hold_time_up": 0.0306, "avr_hold_time_down": 0.0319},
    'VEV_5400': {"strike": 5400, "omega_adj": 0.1545, "avr_hold_time_up": 0.0124, "avr_hold_time_down": 0.1502},
    'VEV_5500': {"strike": 5500, "omega_adj": 0.1899, "avr_hold_time_up": 0.3990, "avr_hold_time_down": 0.3931},
    'VEV_6000': {"strike": 6000, "omega_adj": 1.0000, "avr_hold_time_up": 1.00000, "avr_hold_time_down": 1.00000},
    'VEV_6500': {"strike": 6500, "omega_adj": 1.0000, "avr_hold_time_up": 1.00000, "avr_hold_time_down": 1.00000},
}


MM_OPTIONS = {'VEV_4000'}#, 'VEV_4500', 'VEV_5000'}#, 'VEV_5100'}
EXCLUDED_OPTIONS = {'VEV_6000', 'VEV_6500'}

# stocks: 
# HYDROGEL_PACK large spread, low volume, mean reverting around 10k with Sigma=19 (daily) and Theta: 0.1595 (daily)
#               trending on the short term with (ACF around 0.50 at 800 lags) but mean reverting on the long term (ACF around -0.3 at 5k lags)
# VELVETFRUIT_EXTRACT small spread, high volume, mean reverting around 5250

class Trader:
    MAX_POSITION_OPTIONS = 300
    MAX_POSITION_STOCKS = 200

    # MAX_HALF_SPREAD = 98
    EMPIRICAL_HALF_SPREAD = 0

    # This gamma determines how much we adjust our reservation price based on our current position.
    GEL_GAMMA = 1/12 * MAX_POSITION_STOCKS
    GEL_MEAN = 10000
    GEL_ALPHA = 0.1
    GEL_MEAN_REVERSION_WEIGHT = 0.6

    DAY = 4
    IV_SOLVER_MIN = 1e-4
    IV_SOLVER_MAX = 20.0
    IV_SOLVER_MAX_ITER = 60
    MM_INVENTORY_BUFFER = 20

    FRUIT_MEAN = 5250
    # OMEGA = 18
    OMEGA = 17.93
    # UNDERLYING_OMEGA_ADJ = 0.8206
    UNDERLYING_OMEGA_ADJ = 1.0

    INFORMED_OPTION_SYMBOL = "VEV_4000"
    INFORMED_HISTORY_POINTS = 2000
    # INFORMED_EDGE_DISTANCE = 2
    INFORMED_EDGE_DISTANCE = 0
    # INFORMED_MAX_TRADE_SIZE = 4
    INFORMED_MAX_TRADE_SIZE = 0
    INFORMED_TRADE_LOOKBACK = 100
    INFORMED_HOLD_TIME = 50

    DO_HEDGE = False
    HEDGE_DEAD_BAND = 10

    def __init__(self):
        self.last_gel_mid = self.GEL_MEAN
        self.last_fruit_mid = self.FRUIT_MEAN
        self.gel_ema = self.GEL_MEAN
        # Effective state used for trading (possibly overridden by informed signal)
        self.fruit_state = "neutral"
        # Base OU regime state before any informed-signal override.
        self.mean_reversion_state = "neutral"

        self.informed_hold_remaining = 0
        self.informed_direction = "neutral"
        self.informed_override_active = False
        self.last_vev_mid: Optional[float] = None
        self.vev_mid_history = deque(maxlen=self.INFORMED_HISTORY_POINTS)

        self.option_iv_sums: Dict[str, float] = {}
        self.option_iv_counts: Dict[str, int] = {}

    def bid(self):
        return None

    def encode_trader_data(self, state: TradingState):
        return json.dumps({
            "fruit_mid": self.last_fruit_mid,
            "gel_mid": self.last_gel_mid,
            "gel_ema": self.gel_ema,
            "fruit_state": self.fruit_state,
            "mean_reversion_state": self.mean_reversion_state,
            "informed_hold_remaining": self.informed_hold_remaining,
            "informed_direction": self.informed_direction,
            "last_vev_mid": self.last_vev_mid,
            "vev_mid_history": list(self.vev_mid_history),
            "option_iv_sums": self.option_iv_sums,
            "option_iv_counts": self.option_iv_counts,
        }, separators=(",", ":"))

    def decode_trader_data(self, trader_data_str: str):
        if trader_data_str:
            try:
                trader_data = json.loads(trader_data_str)
            except json.JSONDecodeError:
                trader_data = {}
            self.last_fruit_mid = trader_data.get("fruit_mid", self.FRUIT_MEAN)
            self.last_gel_mid = trader_data.get("gel_mid", self.GEL_MEAN)
            self.gel_ema = trader_data.get("gel_ema", self.GEL_MEAN)
            self.fruit_state = trader_data.get("fruit_state", "neutral")
            self.mean_reversion_state = trader_data.get("mean_reversion_state", self.fruit_state)
            self.informed_hold_remaining = int(trader_data.get("informed_hold_remaining", 0))
            if self.informed_hold_remaining < 0:
                self.informed_hold_remaining = 0
            self.informed_direction = trader_data.get("informed_direction", "neutral")
            if self.informed_direction not in {"bullish", "bearish", "neutral"}:
                self.informed_direction = "neutral"
            self.last_vev_mid = trader_data.get("last_vev_mid")
            self.vev_mid_history = deque(
                trader_data.get("vev_mid_history", []),
                maxlen=self.INFORMED_HISTORY_POINTS,
            )
            raw_iv_sums = trader_data.get("option_iv_sums", {})
            raw_iv_counts = trader_data.get("option_iv_counts", {})
            self.option_iv_sums = {
                symbol: float(value)
                for symbol, value in raw_iv_sums.items()
                if symbol in OPTIONS
            }
            self.option_iv_counts = {
                symbol: int(value)
                for symbol, value in raw_iv_counts.items()
                if symbol in OPTIONS and int(value) > 0
            }
        else:
            self.last_fruit_mid = self.FRUIT_MEAN
            self.last_gel_mid = self.GEL_MEAN
            self.gel_ema = self.GEL_MEAN
            self.fruit_state = "neutral"
            self.mean_reversion_state = "neutral"
            self.informed_hold_remaining = 0
            self.informed_direction = "neutral"
            self.last_vev_mid = None
            self.vev_mid_history = deque(maxlen=self.INFORMED_HISTORY_POINTS)
            self.option_iv_sums = {}
            self.option_iv_counts = {}

    def informed_signal(self, state: TradingState) -> int:
        """Detect VEV_4000 edge trades and return +1 (bullish), -1 (bearish), or 0."""
        option_depth = state.order_depths.get(self.INFORMED_OPTION_SYMBOL)
        if option_depth is None:
            return 0

        vev_mid = self.wall_mid(option_depth)
        if vev_mid is not None:
            self.vev_mid_history.append(vev_mid)
            self.last_vev_mid = vev_mid
        else:
            vev_mid = self.last_vev_mid

        if vev_mid is None or not self.vev_mid_history:
            return 0

        rolling_max = max(self.vev_mid_history)
        rolling_min = min(self.vev_mid_history)
        near_max = vev_mid >= (rolling_max - self.INFORMED_EDGE_DISTANCE)
        near_min = vev_mid <= (rolling_min + self.INFORMED_EDGE_DISTANCE)

        # Ambiguous edge when both are true (common early in the session): do nothing.
        if near_max == near_min:
            return 0

        for trade in state.market_trades.get(self.INFORMED_OPTION_SYMBOL, []):
            if not (state.timestamp - self.INFORMED_TRADE_LOOKBACK <= trade.timestamp <= state.timestamp):
                continue
            if abs(trade.quantity) > self.INFORMED_MAX_TRADE_SIZE:
                continue
            return -1 if near_max else 1
        return 0

    def update_fruit_state_with_informed_override(self, state: TradingState, mid: float) -> None:
        """Update mean-reversion state, then optionally overwrite with informed signal hold."""
        self.informed_override_active = False
        upper_trigger = self.FRUIT_MEAN + self.OMEGA * self.UNDERLYING_OMEGA_ADJ
        lower_trigger = self.FRUIT_MEAN - self.OMEGA * self.UNDERLYING_OMEGA_ADJ
        bullish_unwind_trigger = self.FRUIT_MEAN + self.HEDGE_DEAD_BAND
        bearish_unwind_trigger = self.FRUIT_MEAN - self.HEDGE_DEAD_BAND

        if self.DO_HEDGE:
            if self.mean_reversion_state == "neutral":
                if mid > upper_trigger:
                    self.mean_reversion_state = "bearish"
                elif mid < lower_trigger:
                    self.mean_reversion_state = "bullish"
            elif self.mean_reversion_state == "bullish":
                if mid >= bullish_unwind_trigger:
                    self.mean_reversion_state = "neutral"
            elif self.mean_reversion_state == "bearish":
                if mid <= bearish_unwind_trigger:
                    self.mean_reversion_state = "neutral"
        else:
            if self.mean_reversion_state == "neutral":
                if mid > upper_trigger:
                    self.mean_reversion_state = "bearish"
                elif mid < lower_trigger:
                    self.mean_reversion_state = "bullish"
            elif self.mean_reversion_state == "bullish":
                if mid > upper_trigger:
                    self.mean_reversion_state = "bearish"
            elif self.mean_reversion_state == "bearish":
                if mid < lower_trigger:
                    self.mean_reversion_state = "bullish"

        informed_sig = self.informed_signal(state)
        if informed_sig != 0:
            self.informed_direction = "bullish" if informed_sig > 0 else "bearish"
            self.informed_hold_remaining = self.INFORMED_HOLD_TIME

        if self.informed_hold_remaining > 0:
            self.informed_override_active = True
            self.fruit_state = self.informed_direction
            self.informed_hold_remaining -= 1
        else:
            self.fruit_state = self.mean_reversion_state

    def wall_mid(self, order_depth: OrderDepth):
        """Will find the mid of the second best bid/ask if available, otherwise the mid of the best bid/ask."""
        bids = order_depth.buy_orders
        asks = order_depth.sell_orders
        
        bid_prices = sorted(bids.keys(), reverse=True) if bids else []
        ask_prices = sorted(asks.keys()) if asks else []
        
        # Try to use second best bid/ask
        if len(bid_prices) >= 2 and len(ask_prices) >= 2:
            return (bid_prices[1] + ask_prices[1]) / 2
        # Fall back to best bid/ask
        elif len(bid_prices) >= 1 and len(ask_prices) >= 1:
            return (bid_prices[0] + ask_prices[0]) / 2
        else:
            return None

    def best_bid_ask(self, order_depth: OrderDepth):
        bids = order_depth.buy_orders
        asks = order_depth.sell_orders
        best_bid = max(bids.keys()) if bids else None
        best_ask = min(asks.keys()) if asks else None
        return best_bid, best_ask

    def best_bid_ask_qty(self, order_depth: OrderDepth):
        bids = order_depth.buy_orders
        asks = order_depth.sell_orders
        best_bid = max(bids.keys()) if bids else None
        best_ask = min(asks.keys()) if asks else None
        best_bid_qty = bids[best_bid] if best_bid is not None else None
        best_ask_qty = asks[best_ask] if best_ask is not None else None
        return best_bid, best_ask, best_bid_qty, best_ask_qty

    def simulate_fill(self, order_depth: OrderDepth, price: int, quantity: int) -> OrderDepth:
        """Simulate how the order book would look like if we got filled on a given price and quantity."""
        new_buy_orders = order_depth.buy_orders.copy()
        new_sell_orders = order_depth.sell_orders.copy()

        if quantity > 0:
            # Simulate a buy order getting filled, which would reduce the quantity on the sell side
            if price in new_sell_orders:
                new_sell_orders[price] -= quantity
                if new_sell_orders[price] <= 0:
                    del new_sell_orders[price]
        elif quantity < 0:
            # Simulate a sell order getting filled, which would reduce the quantity on the buy side
            if price in new_buy_orders:
                new_buy_orders[price] += quantity  # quantity is negative, so this reduces the buy quantity
                if new_buy_orders[price] <= 0:
                    del new_buy_orders[price]

        od = OrderDepth()
        od.buy_orders = new_buy_orders
        od.sell_orders = new_sell_orders
        return od
    
    def skew_adjustment(self, position: int, max_position: int, gamma: float):
        """Calculate the inventory skew adjustment based on a cubic function."""
        if max_position == 0:
            return 0
        normalized_position = position / max_position
        if normalized_position < 0:
            return -gamma * normalized_position**2
        return gamma * normalized_position**2
    
    def hydrogel_orders(self, state: TradingState):
        orders: List[Order] = []
        position = state.position.get("HYDROGEL_PACK", 0)
        order_depth = state.order_depths["HYDROGEL_PACK"]
        best_bid, best_ask, bb_qty, ba_qty = self.best_bid_ask_qty(order_depth)
        
        mid = self.wall_mid(order_depth)
        if mid is None:
            mid = self.last_gel_mid
            
        self.last_gel_mid = mid

        # 1. Update Short-Term Trend (EMA)
        self.gel_ema = self.GEL_ALPHA * mid + (1 - self.GEL_ALPHA) * self.gel_ema

        # 2. Calculate Smart Fair Value
        # Blend the short-term trend (EMA) and the long-term mean (10000)
        # Give more weight to the mean as price deviates further from it
        mean_reversion_weight = self.GEL_MEAN_REVERSION_WEIGHT
        base_fv = (mean_reversion_weight * self.GEL_MEAN) + ((1 - mean_reversion_weight) *(2*mid - self.gel_ema))
        
        # Apply Inventory Skew
        # fv = base_fv - ((position/self.MAX_POSITION_STOCKS)**3 * self.GEL_GAMMA)
        fv = base_fv - self.skew_adjustment(position, self.MAX_POSITION_STOCKS, self.GEL_GAMMA)

        bid_size = self.MAX_POSITION_STOCKS - position
        ask_size = -self.MAX_POSITION_STOCKS - position
        
        # 3. TAKER LOGIC (Only cross spread if the edge is MASSIVE)
        # In a low-volume, high-spread asset, taking liquidity is very expensive.
        if best_ask is not None and ba_qty is not None and best_ask < fv - 2: # Require at least 2 ticks of edge
            size = min(bid_size, -ba_qty)
            if size > 0:
                orders.append(Order("HYDROGEL_PACK", best_ask, size))
                bid_size -= size
                order_depth = self.simulate_fill(order_depth, best_ask, size)
                best_bid, best_ask, bb_qty, ba_qty = self.best_bid_ask_qty(order_depth)

        if best_bid is not None and bb_qty is not None and best_bid > fv + 2:
            size = max(ask_size, -bb_qty)  
            if size < 0:
                orders.append(Order("HYDROGEL_PACK", best_bid, size))
                ask_size -= size
                order_depth = self.simulate_fill(order_depth, best_bid, size)
                best_bid, best_ask, bb_qty, ba_qty = self.best_bid_ask_qty(order_depth)
                
        # 4. MAKER LOGIC (Quote near the actual spread)
        # Instead of 98, quote at FV +/- (Half Spread - 1) to compete for priority
        quote_bid = floor(fv - self.EMPIRICAL_HALF_SPREAD + 1)
        if best_bid is not None:
            # Penny the best bid if it makes sense, but don't overpay for FV
            quote_bid = min(quote_bid, best_bid + 1)
            # Ensure we don't cross the ask
            quote_bid = min(quote_bid, best_ask - 1 if best_ask else quote_bid)

        if bid_size > 0:
            orders.append(Order("HYDROGEL_PACK", quote_bid, bid_size))

        quote_ask = ceil(fv + self.EMPIRICAL_HALF_SPREAD - 1)
        if best_ask is not None:
            # Penny the best ask
            quote_ask = max(quote_ask, best_ask - 1)
            # Ensure we don't cross the bid
            quote_ask = max(quote_ask, best_bid + 1 if best_bid else quote_ask)

        if ask_size < 0:
            orders.append(Order("HYDROGEL_PACK", quote_ask, ask_size))

        # logger.print(
        #     f"HYDROGEL_PACK fair={fv:.2f} pos={position} reservation=0.00",
        #     f"PLOT: bid={quote_bid}, ask={quote_ask}, fv={fv:.2f}, skew_adj=0.0",
        # )
        return orders


    def bs_call_price(self, S: float, K: float, T: float, sigma: float) -> float:
        if T <= 0 or sigma <= 0:
            return max(0.0, S - K)
        d1 = (math.log(S / K) + 0.5 * sigma**2 * T) / (sigma * math.sqrt(T))
        d2 = d1 - sigma * math.sqrt(T)
        return S * NormalDist().cdf(d1) - K * NormalDist().cdf(d2)

    def option_tau(self, timestamp: int) -> float:
        elapsed_years = timestamp / 1_000_000 / 365 + self.DAY / 365
        return 7 / 365 - elapsed_years

    def smile_iv(self, symbol: str) -> float:
        strike = OPTIONS[symbol]["strike"]
        spot = max(float(self.last_fruit_mid), 1.0)
        moneyness = math.log(spot / strike)
        return 0.255628 + 8.799657 * moneyness**2

    def ensure_option_iv_seed(self, symbol: str) -> None:
        if self.option_iv_counts.get(symbol, 0) > 0:
            return
        self.option_iv_sums[symbol] = self.smile_iv(symbol)
        self.option_iv_counts[symbol] = 1

    def average_option_iv(self, symbol: str) -> float:
        self.ensure_option_iv_seed(symbol)
        return self.option_iv_sums[symbol] / self.option_iv_counts[symbol]

    def estimate_implied_vol(self, symbol: str, option_price: float, timestamp: int) -> Optional[float]:
        strike = OPTIONS[symbol]["strike"]
        spot = max(float(self.last_fruit_mid), 1.0)
        tau = self.option_tau(timestamp)
        if tau <= 0 or option_price <= 0:
            return None
        intrinsic = max(0.0, spot - strike)
        if option_price < intrinsic or option_price >= spot:
            return None
        low, high = self.IV_SOLVER_MIN, self.IV_SOLVER_MAX
        if option_price <= self.bs_call_price(spot, strike, tau, low):
            return low
        high_price = self.bs_call_price(spot, strike, tau, high)
        while high_price < option_price and high < 10.0:
            high *= 2
            high_price = self.bs_call_price(spot, strike, tau, high)
        if high_price < option_price:
            return None
        for _ in range(self.IV_SOLVER_MAX_ITER):
            mid_iv = (low + high) / 2
            mid_price = self.bs_call_price(spot, strike, tau, mid_iv)
            if abs(mid_price - option_price) < 1e-6:
                return mid_iv
            if mid_price < option_price:
                low = mid_iv
            else:
                high = mid_iv
        return (low + high) / 2

    def update_option_iv_estimate(self, symbol: str, option_price: float, timestamp: int) -> None:
        iv = self.estimate_implied_vol(symbol, option_price, timestamp)
        if iv is None:
            return
        self.ensure_option_iv_seed(symbol)
        self.option_iv_sums[symbol] += iv
        self.option_iv_counts[symbol] += 1

    def option_price_est(self, symbol: str, timestamp: int) -> float:
        K = OPTIONS[symbol]["strike"]
        S = max(float(self.last_fruit_mid), 1.0)
        tau = self.option_tau(timestamp)
        iv = self.average_option_iv(symbol)
        return self.bs_call_price(S, K, tau, iv)

    def option_mean_price(self, symbol: str, timestamp: int) -> float:
        K = OPTIONS[symbol]["strike"]
        S = float(self.FRUIT_MEAN)
        tau = self.option_tau(timestamp)
        iv = self.average_option_iv(symbol)
        return self.bs_call_price(S, K, tau, iv)

    def option_long_threshold(self, symbol: str, timestamp: int) -> float:
        """BS call price at FRUIT_MEAN - OMEGA: only buy if best_ask is at or below this."""
        K = OPTIONS[symbol]["strike"]
        omega_adj = OPTIONS[symbol]["omega_adj"]
        avr_hold_time_down = OPTIONS[symbol]["avr_hold_time_down"]
        S = max(float(self.FRUIT_MEAN - self.OMEGA * omega_adj), 1.0)
        tau = self.option_tau(timestamp) + avr_hold_time_down/365
        iv = self.average_option_iv(symbol)
        return self.bs_call_price(S, K, tau, iv)

    def option_short_threshold(self, symbol: str, timestamp: int) -> float:
        """BS call price at FRUIT_MEAN + OMEGA: only sell if best_bid is at or above this."""
        K = OPTIONS[symbol]["strike"]
        omega_adj = OPTIONS[symbol]["omega_adj"]
        avr_hold_time_up = OPTIONS[symbol]["avr_hold_time_up"]
        S = float(self.FRUIT_MEAN + self.OMEGA * omega_adj)
        tau = self.option_tau(timestamp) + avr_hold_time_up/365
        iv = self.average_option_iv(symbol)
        return self.bs_call_price(S, K, tau, iv)


    def orders_to_reach_target(
        self,
        symbol: str,
        order_depth: OrderDepth,
        current_position: int,
        target: int,
        max_buy_price: Optional[int] = None,
        min_sell_price: Optional[int] = None,
    ) -> List[Order]:
        """Generate market-taking orders to move position from current to target."""
        orders: List[Order] = []
        diff = target - current_position
        if diff > 0:
            for ask_price in sorted(order_depth.sell_orders.keys()):
                if diff <= 0:
                    break
                if max_buy_price is not None and ask_price > max_buy_price:
                    continue
                available = -order_depth.sell_orders[ask_price]
                qty = min(diff, available)
                if qty > 0:
                    orders.append(Order(symbol, ask_price, qty))
                    diff -= qty
        elif diff < 0:
            for bid_price in sorted(order_depth.buy_orders.keys(), reverse=True):
                if diff >= 0:
                    break
                if min_sell_price is not None and bid_price < min_sell_price:
                    continue
                available = order_depth.buy_orders[bid_price]
                qty = min(-diff, available)
                if qty > 0:
                    orders.append(Order(symbol, bid_price, -qty))
                    diff += qty
        return orders

    def option_regime_orders(self, state: TradingState, symbol: str) -> List[Order]:
        """Per-option orders: threshold-gated directional takes plus passive MM for MM_OPTIONS."""
        orders: List[Order] = []
        order_depth = state.order_depths.get(symbol)
        if order_depth is None:
            return orders

        position = state.position.get(symbol, 0)
        best_bid, best_ask, bb_qty, ba_qty = self.best_bid_ask_qty(order_depth)
        is_mm = symbol in MM_OPTIONS
        mm_half_buffer = self.MM_INVENTORY_BUFFER // 2
        directional_max = self.MAX_POSITION_OPTIONS - (mm_half_buffer if is_mm else 0)

        long_thr = self.option_long_threshold(symbol, state.timestamp)
        short_thr = self.option_short_threshold(symbol, state.timestamp)
        option_mean = self.option_mean_price(symbol, state.timestamp)
        wall_mid = self.wall_mid(order_depth)
        informed_override_active = self.informed_override_active and self.fruit_state in {"bullish", "bearish"}
        take_max_buy_price: Optional[int] = None
        take_min_sell_price: Optional[int] = None

        # Determine directional target
        if self.fruit_state == "bullish":
            if informed_override_active:
                # During informed hold, force directional option alignment.
                directional_target = max(position, directional_max)
            elif best_ask is not None and best_ask <= long_thr:
                # In bullish regime, build to at least directional_max but do not
                # unwind passive fills that move us higher.
                directional_target = max(position, directional_max)
                # Only take ask levels that still clear the long threshold.
                take_max_buy_price = floor(long_thr)
            else:
                directional_target = position  # threshold not met; hold
        elif self.fruit_state == "bearish":
            if informed_override_active:
                # During informed hold, force directional option alignment.
                directional_target = min(position, -directional_max)
            elif best_bid is not None and best_bid >= short_thr:
                # In bearish regime, build to at least -directional_max but do not
                # unwind passive fills that move us lower.
                directional_target = min(position, -directional_max)
                # Only take bid levels that still clear the short threshold.
                take_min_sell_price = ceil(short_thr)
            else:
                directional_target = position  # threshold not met; hold
        else:  # neutral: unwind to flat
            if is_mm:
                buffer = self.MM_INVENTORY_BUFFER
                if position > buffer:
                    directional_target = buffer
                    take_min_sell_price = ceil(option_mean)
                    if wall_mid is not None:
                        take_min_sell_price = min(take_min_sell_price, ceil(wall_mid - 2))
                elif position < -buffer:
                    directional_target = -buffer
                    take_max_buy_price = floor(option_mean)
                    if wall_mid is not None:
                        take_max_buy_price = max(take_max_buy_price, floor(wall_mid + 2))
                else:
                    directional_target = position
            else:
                if position > 0:
                    directional_target = 0
                    take_min_sell_price = ceil(option_mean)
                elif position < 0:
                    directional_target = 0
                    take_max_buy_price = floor(option_mean)
                else:
                    directional_target = position

        # Taking / unwinding orders
        if directional_target != position:
            take_orders = self.orders_to_reach_target(
                symbol,
                order_depth,
                position,
                directional_target,
                max_buy_price=take_max_buy_price,
                min_sell_price=take_min_sell_price,
            )
            orders.extend(take_orders)

        # Side-specific exposure after directional orders.
        # We treat buy-side and sell-side fill risk independently and do not
        # net opposite-side orders against each other when computing limits.
        long_exposure = position
        short_exposure = position
        for order in orders:
            if order.quantity > 0:
                long_exposure += order.quantity
            elif order.quantity < 0:
                short_exposure += order.quantity

        # Passive market making for MM_OPTIONS (always active in all regimes)

        fv = self.option_price_est(symbol, state.timestamp)
        quote_bid = None
        quote_ask = None
        if is_mm:
            allow_quote_bid = False
            allow_quote_ask = False
            bid_size = 0
            ask_size = 0

            if self.fruit_state == "bullish":
                # Maintain inventory in [MAX - buffer, MAX] while quoting both sides
                # inside the band and shutting off one side at each edge.
                band_low = self.MAX_POSITION_OPTIONS - self.MM_INVENTORY_BUFFER
                band_high = self.MAX_POSITION_OPTIONS
                bid_size = max(0, band_high - long_exposure)
                ask_size = min(0, band_low - short_exposure)
                allow_quote_bid = bid_size > 0
                allow_quote_ask = ask_size < 0

            elif self.fruit_state == "bearish":
                # Symmetric short band: [-MAX, -(MAX - buffer)].
                band_low = -self.MAX_POSITION_OPTIONS
                band_high = -(self.MAX_POSITION_OPTIONS - self.MM_INVENTORY_BUFFER)
                bid_size = max(0, band_high - long_exposure)
                ask_size = min(0, band_low - short_exposure)
                allow_quote_bid = bid_size > 0
                allow_quote_ask = ask_size < 0

            if self.fruit_state == "neutral":
                bid_size = self.MAX_POSITION_OPTIONS - long_exposure
                ask_size = -self.MAX_POSITION_OPTIONS - short_exposure
                allow_quote_bid = long_exposure < self.MM_INVENTORY_BUFFER
                allow_quote_ask = short_exposure > -self.MM_INVENTORY_BUFFER

            quote_bid = floor(fv)
            if best_bid is not None:
                quote_bid = min(quote_bid, best_bid + 1)
            if best_ask is not None:
                quote_bid = min(quote_bid, best_ask - 1)
            if bid_size > 0 and allow_quote_bid:
                orders.append(Order(symbol, quote_bid, bid_size))
                long_exposure += bid_size

            quote_ask = ceil(fv)
            if best_ask is not None:
                quote_ask = max(quote_ask, best_ask - 1)
            if best_bid is not None:
                quote_ask = max(quote_ask, best_bid + 1)
            if ask_size < 0 and allow_quote_ask:
                orders.append(Order(symbol, quote_ask, ask_size))
                short_exposure += ask_size

        logger.print(
            f"{symbol} state={self.fruit_state} pos={position},",
            f"PLOT: pos={position}, long_thr={long_thr:.4f}, short_thr={short_thr:.4f}, bid={quote_bid}, ask={quote_ask}, fv={fv:.2f}",
        )
        return orders

    def fruit_and_options_orders(self, state: TradingState) -> Dict[str, List[Order]]:
        """OU mean-reversion regime for VELVETFRUIT_EXTRACT and its options.

        Fruit: enter/exit based on ±OMEGA band around FRUIT_MEAN.
        Options: each uses its own threshold (BS price at ±OMEGA fruit level).
                 MM_OPTIONS also always market-make; EXCLUDED_OPTIONS are skipped.
        """
        result: Dict[str, List[Order]] = {}

        fruit_depth = state.order_depths.get("VELVETFRUIT_EXTRACT")
        if fruit_depth is None:
            return result

        mid = self.wall_mid(fruit_depth)
        if mid is None:
            mid = self.last_fruit_mid
        self.last_fruit_mid = mid

        # Base OU regime can be overwritten by informed-trader direction for a hold period.
        self.update_fruit_state_with_informed_override(state, mid)

        if self.fruit_state == "bullish":
            fruit_target = self.MAX_POSITION_STOCKS
        elif self.fruit_state == "bearish":
            fruit_target = -self.MAX_POSITION_STOCKS
        else:
            fruit_target = 0

        # Fruit orders
        fruit_position = state.position.get("VELVETFRUIT_EXTRACT", 0)
        fruit_orders = self.orders_to_reach_target(
            "VELVETFRUIT_EXTRACT", fruit_depth, fruit_position, fruit_target
        )
        if fruit_orders:
            result["VELVETFRUIT_EXTRACT"] = fruit_orders

        # Update IV estimates for all tradeable options
        for symbol in OPTIONS:
            if symbol in EXCLUDED_OPTIONS:
                continue
            option_depth = state.order_depths.get(symbol)
            if option_depth is None:
                continue
            option_mid = self.wall_mid(option_depth)
            if option_mid is None:
                continue
            self.update_option_iv_estimate(symbol, option_mid, state.timestamp)

        # Options orders
        for symbol in OPTIONS:
            if symbol in EXCLUDED_OPTIONS:
                continue
            option_orders = self.option_regime_orders(state, symbol)
            if option_orders:
                result[symbol] = option_orders

        # logger.print(
        #     f"VELVETFRUIT_EXTRACT state={self.fruit_state} mid={mid:.2f} omega={self.OMEGA:.2f} fruit_target={fruit_target}",
        #     f"PLOT: mid={mid:.4f}, fruit_target={fruit_target}, state={self.fruit_state}",
        # )
        return result


    def run(self, state: TradingState):
        self.decode_trader_data(state.traderData)
        orders = {}

        if "HYDROGEL_PACK" in state.order_depths:
            orders["HYDROGEL_PACK"] = self.hydrogel_orders(state)

        orders.update(self.fruit_and_options_orders(state))

        traderData = self.encode_trader_data(state)
        conversions = 0
        logger.flush(state, orders, conversions, traderData)
        return orders, conversions, traderData
    


class Logger:
    """Visualizer-compatible logger kept inside trader.py for submission use."""

    def __init__(self) -> None:
        self.logs = ""
        self.max_log_length = 100000

    def print(self, *objects: Any, sep: str = " ", end: str = "\n") -> None:
        """Collect one human-readable log line for the current backtest tick."""
        self.logs += sep.join(map(str, objects)) + end

    def flush(
        self,
        state: TradingState,
        orders: Dict[str, List[Order]],
        conversions: int,
        trader_data: str,
    ) -> None:
        """Emit a single compact JSON payload that the backtester can persist."""
        base_length = len(
            self.to_json(
                [
                    self.compress_state(state, ""),
                    self.compress_orders(orders),
                    conversions,
                    "",
                    "",
                ]
            )
        )

        max_item_length = (self.max_log_length - base_length) // 3

        print(
            self.to_json(
                [
                    self.compress_state(state, self.truncate(state.traderData, max_item_length)),
                    self.compress_orders(orders),
                    conversions,
                    self.truncate(trader_data, max_item_length),
                    self.truncate(self.logs, max_item_length),
                ]
            )
        )

        self.logs = ""

    def compress_state(self, state: TradingState, trader_data: str) -> list[Any]:
        """Mirror the Prosperity log schema used by the visualizer parser."""
        return [
            state.timestamp,
            trader_data,
            self.compress_listings(state.listings),
            self.compress_order_depths(state.order_depths),
            self.compress_trades(state.own_trades),
            self.compress_trades(state.market_trades),
            state.position,
            self.compress_observations(state.observations),
        ]

    def compress_listings(self, listings: Dict[str, Listing]) -> List[List[Any]]:
        """Flatten listings into the `[symbol, product, denomination]` tuple layout."""
        return [[listing.symbol, listing.product, listing.denomination] for listing in listings.values()]

    def compress_order_depths(self, order_depths: Dict[str, OrderDepth]) -> Dict[str, List[Any]]:
        """Serialize the visible book on each symbol as buy/sell price maps."""
        return {
            symbol: [order_depth.buy_orders, order_depth.sell_orders]
            for symbol, order_depth in order_depths.items()
        }

    def compress_trades(self, trades: Dict[str, List[Trade]]) -> List[List[Any]]:
        """Flatten trade history so every trade ends up in the same timestamp row."""
        compressed: List[List[Any]] = []
        for trade_list in trades.values():
            for trade in trade_list:
                compressed.append(
                    [
                        trade.symbol,
                        trade.price,
                        trade.quantity,
                        trade.buyer,
                        trade.seller,
                        trade.timestamp,
                    ]
                )
        return compressed

    def compress_observations(self, observations: Observation) -> list[Any]:
        """Pack conversion and plain-value observations into the expected row shape."""
        conversion_observations = {}
        for product, observation in observations.conversionObservations.items():
            conversion_observations[product] = [
                observation.bidPrice,
                observation.askPrice,
                observation.transportFees,
                observation.exportTariff,
                observation.importTariff,
            ]

        return [observations.plainValueObservations, conversion_observations]

    def compress_orders(self, orders: Dict[str, List[Order]]) -> List[List[Any]]:
        """Flatten the order batches so they are easy to parse back from JSON."""
        compressed: List[List[Any]] = []
        for order_list in orders.values():
            for order in order_list:
                compressed.append([order.symbol, order.price, order.quantity])
        return compressed

    def to_json(self, value: Any) -> str:
        """Encode Prosperity datatypes into compact JSON without extra spaces."""
        return json.dumps(value, cls=ProsperityEncoder, separators=(",", ":"))

    def truncate(self, value: str, max_length: int) -> str:
        """Shorten long strings while keeping the final JSON payload valid."""
        lo, hi = 0, min(len(value), max_length)
        out = ""

        while lo <= hi:
            mid = (lo + hi) // 2
            candidate = value[:mid]
            if len(candidate) < len(value):
                candidate += "..."

            if len(json.dumps(candidate)) <= max_length:
                out = candidate
                lo = mid + 1
            else:
                hi = mid - 1

        return out

def format_plot_payload(*, namespace: Optional[str] = None, **fields: Any) -> str:
    """Format structured logger metadata for the analysis visualizer.

    Use bare `PLOT:` for fields that should appear in the main tooltip.
    Use `PLOT[module]:` when you want the visualizer to render a separate
    module chart below the main plot later on.
    """
    # Keep the payload human-editable so traders can add fields without touching
    # the visualizer code as long as they stick to simple `key=value` pairs.
    parts: List[str] = []
    for key, value in fields.items():
        if isinstance(value, float):
            formatted_value = f"{value:.4f}".rstrip("0").rstrip(".")
        elif isinstance(value, bool):
            formatted_value = "true" if value else "false"
        else:
            formatted_value = str(value)
        parts.append(f"{key}={formatted_value}")

    prefix = "PLOT:" if namespace is None else f"PLOT[{namespace}]:"
    return f"{prefix} " + ", ".join(parts)
logger = Logger()